name: banco
authors: [myth-MC, U8092]
version: '${project.version}'
api-version: 1.20

main: ovh.mythmc.banco.bukkit.BancoBukkitPlugin
softdepend: [ PlaceholderAPI, social, gestalt ]
loadbefore:
  - Vault
  - Essentials

libraries:
  - net.kyori:adventure-api:4.24.0
  - net.kyori:adventure-platform-bukkit:4.4.1
  - net.kyori:adventure-text-minimessage:4.24.0

permissions:
  # Basic nodes
  banco.user:
    default: true
    children:
      banco.use.help: true
      banco.use.balance: true
      banco.use.balancetop: true
      banco.use.balancechange: true
      banco.use.pay: true
  banco.admin:
    default: op
    children:
      banco.use.banco.encode: true
      banco.use.banco.deposit: true
      bnaco.use.banco.set: true
      bnaco.use.banco.withdraw: true
      banco.use.banco.dump: true
      banco.use.banco.info: true
      banco.use.banco.reload: true
  # Commands (misc)
  banco.use.help:
    default: true
  banco.use.balance:
    default: true
  banco.use.balancetop:
    default: true
  banco.use.balancechange:
    default: true
  banco.use.pay:
    default: true
  # Commands (/banco)
  banco.use.banco.encode:
    default: op
  banco.use.banco.deposit:
    default: op
  banco.use.banco.set:
    default: op
  banco.use.banco.withdraw:
    default: op
  banco.use.banco.dump:
    default: op
  banco.use.banco.info:
    default: op
  banco.use.banco.reload:
    default: op