name: banco
authors:
  - myth-MC
  - U8092
version: '${project.version}'
api-version: '1.21'

main: ovh.mythmc.banco.paper.BancoPaperPlugin
folia-supported: true

dependencies:
  server:
    Vault:
      load: AFTER
      required: true
      join-classpath: true
    Essentials:
      load: AFTER
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    gestalt:
      load: OMIT
      required: false
      join-classpath: true
    social:
      load: OMIT
      required: false
      join-classpath: true
    ItemsAdder:
      load: OMIT
      required: false
      join-classpath: true
    Oraxen:
      load: OMIT
      required: false
      join-classpath: true
    MythicMobs:
      load: OMIT
      required: false
      join-classpath: true
    Nova:
      load: OMIT
      required: false
      join-classpath: true

permissions:
  banco.user:
    default: true
  banco.admin:
    default: op