name: banco
authors:
  - myth-MC
  - U8092
version: '${project.version}'
api-version: '1.21.7'

main: ovh.mythmc.banco.paper.BancoPaperPlugin
folia-supported: true

dependencies:
  server:
    Vault:
      load: AFTER
      required: true
      join-classpath: true
    Essentials:
      load: AFTER
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    gestalt:
      load: OMIT
      required: false
      join-classpath: true
    social:
      load: OMIT
      required: false
      join-classpath: true
    ItemsAdder:
      load: OMIT
      required: false
      join-classpath: true
    Oraxen:
      load: OMIT
      required: false
      join-classpath: true
    MythicMobs:
      load: OMIT
      required: false
      join-classpath: true
    Nova:
      load: OMIT
      required: false
      join-classpath: true
    Nexo:
      load: OMIT
      required: false
      join-classpath: true
    Slimefun:
      load: OMIT
      required: false
      join-classpath: true

permissions:
  # Basic nodes
  banco.user:
    default: true
    children:
      banco.use.help: true
      banco.use.balance: true
      banco.use.balancetop: true
      banco.use.balancechange: true
      banco.use.pay: true
      banco.use.transactions: true
  banco.admin:
    default: op
    children:
      banco.use.banco.encode: true
      banco.use.banco.deposit: true
      bnaco.use.banco.set: true
      bnaco.use.banco.withdraw: true
      banco.use.banco.dump: true
      banco.use.banco.info: true
      banco.use.banco.reload: true
      banco.use.banco.debug.forcesave: true
  # Commands (misc)
  banco.use.help:
    default: true
  banco.use.balance:
    default: true
  banco.use.balancetop:
    default: true
  banco.use.balancechange:
    default: true
  banco.use.pay:
    default: true
  banco.use.transactions:
    default: true
  # Commands (/banco)
  banco.use.banco.encode:
    default: op
  banco.use.banco.deposit:
    default: op
  banco.use.banco.set:
    default: op
  banco.use.banco.withdraw:
    default: op
  banco.use.banco.dump:
    default: op
  banco.use.banco.info:
    default: op
  banco.use.banco.reload:
    default: op
  banco.use.banco.debug.forcesave:
    default: op